{% set name = "pyiron_base" %}
{% set version = "0.6.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_base-{{ version }}.tar.gz
  sha256: 619aa9bddefe30eb898a4efbbca81e75fa4b97cf81ec7e476ad9bf07588eafad
  patches:
    - gitpython.patch

build:
  entry_points:
    - pyiron=pyiron_base.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - dill >=0.3.7
    - gitpython >=3.1.37
    - h5io >=0.1.9
    - h5py >=3.10.0
    - jinja2 >=3.1.2
    - numpy >=1.24.4  # for numba and pytorch compatibility
    - pandas >=2.1.1
    - pint >=0.22
    - psutil >=5.9.5
    - pyfileindex >=0.0.12
    - pysqa >=0.1.3
    - sqlalchemy >=2.0.22
    - pytables >=3.9.1
    - tqdm >=4.66.1
    - traitlets >=5.11.2

test:
  imports:
    - pyiron_base
  commands:
    - pip check
    - pyiron --help
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_base
  summary: pyiron_base - an integrated development environment (IDE) for computational science.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
