{% set name = "pyiron_base" %}
{% set version = "0.6.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_base-{{ version }}.tar.gz
  sha256: 8e1b322f6cce587f642b0308adb93794d191b0c4140551d4674ae8bd819af56a

build:
  entry_points:
    - pyiron=pyiron_base.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - cloudpickle
    - gitpython
    - h5io_browser
    - h5py
    - jinja2
    - numpy
    - pandas
    - pint
    - psutil
    - pyfileindex
    - pysqa
    - sqlalchemy
    - pytables
    - tqdm
    - traitlets
    - versioneer
    - toml
  run:
    - cloudpickle >=2.0.0,<=3.0.0
    - python >=3.8
    - gitpython >=3.1.23,<=3.1.40
    - h5io_browser >=0.0.2,<=0.0.4
    - h5py >=3.6.0,<=3.10.0
    - jinja2 >=2.11.3,<=3.1.2
    - numpy >=1.23.5,<=1.26.2
    - pandas >=2.0.0,<=2.1.4
    - pint >=0.18,<=0.23
    - psutil >=5.8.0,<=5.9.7
    - pyfileindex >=0.0.16,<=0.0.19
    - pysqa >=0.1.5,<=0.1.9
    - sqlalchemy >=2.0.22,<=2.0.25
    - pytables >=3.6.1,<=3.9.2
    - tqdm >=4.44.0,<=4.66.1
    - traitlets >=5.1.1,<=5.14.0

test:
  imports:
    - pyiron_base
  commands:
    - pip check
    - pyiron --help
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_base
  summary: pyiron_base - an integrated development environment (IDE) for computational science.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
