{% set name = "pyiron_base" %}
{% set version = "0.2.17" %}
{% set sha256 = "e72e5e17e7b68bd84cd5d934d3756fe2ea7d725940244d7496110fba48b60316" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pyiron = pyiron_base.cli:main

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - dill >=0.3.4
    - future >=0.18.2
    - gitpython >=3.1.18
    - git
    - h5io >=0.1.2
    - h5py >=3.2.1
    - numpy >=1.20.3
    - pandas >=1.2.4
    - pathlib2 >=2.3.5
    - psutil >=5.8.0
    - pyfileindex >=0.0.6
    - pysqa >=0.0.15
    - sqlalchemy >=1.4.18
    - pytables >=3.6.1
    - tqdm >=4.61.1

test:
  imports:
    - pyiron_base
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_base
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Core module for pyiron - an integrated development environment (IDE) for computational materials science.
  description: |
    pyiron was initially developed in the Computational Materials Design department of Joerg Neugebauer at the
    Max Planck Insitut für Eisenforschung (Max Planck Insitute for iron research) as a framework for ab initio
    thermodynamics. In collaboration with the Interdisciplinary Centre for Advanced Materials Simulation (ICAMS)
    the framework was recently extended for high throughput applications resulting in the opensource release of
    pyiron.
  doc_url: https://pyiron.org
  dev_url: https://github.com/pyiron

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - muh-hassani
    - niklassiemer
