{% set name = "pyiron_base" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_base-{{ version }}.tar.gz
  sha256: 877b65fecdf35affc25b8b6a63589a72d9f990cb2cb3fc2294820403f8492209

build:
  entry_points:
    - pyiron=pyiron_base.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - cloudpickle
    - gitpython
    - h5io_browser
    - h5py
    - jinja2
    - numpy
    - pandas
    - pint
    - psutil
    - pyfileindex
    - pysqa
    - sqlalchemy
    - pytables
    - tqdm
    - traitlets
    - versioneer
    - toml
  run:
    - cloudpickle >=2.0.0,<=3.0.0
    - python >=3.8
    - gitpython >=3.1.23,<=3.1.41
    - h5io_browser >=0.0.6,<=0.0.7
    - h5py >=3.6.0,<=3.10.0
    - jinja2 >=2.11.3,<=3.1.3
    - numpy >=1.23.5,<=1.26.3
    - pandas >=2.0.0,<=2.2.0
    - pint >=0.18,<=0.23
    - psutil >=5.8.0,<=5.9.8
    - pyfileindex >=0.0.16,<=0.0.21
    - pysqa >=0.1.5,<=0.1.11
    - sqlalchemy >=2.0.22,<=2.0.25
    - pytables >=3.6.1,<=3.9.2
    - tqdm >=4.44.0,<=4.66.1
    - traitlets >=5.1.1,<=5.14.1

test:
  imports:
    - pyiron_base
  commands:
    - pip check
    - pyiron --help
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_base
  summary: pyiron_base - an integrated development environment (IDE) for computational science.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
