travis:
  secure:
    BINSTAR_TOKEN: cXbBnw1qJvWN8n80NOmC3d/kPRUkBVm0WS+jUXc4pvLwQ5CWYL4waRNoawNo2a+BEkfTf6Ni+o7mC1Rc30Y7iJsyMzK0b5+iQtBeiEpMwZhONLGv86ppFau1hAWgibzmWxE2eb/6Wup4Zs/43YfYUKMyeHrPIAWfaEXOb6gnui8Z64ZJsls3uKP6Lvf0wNDDqSM/ZJ9L5zAq2J9KrqCsMeBn1phiVpn0ti7BntkclOeG3pgR1a3C0jxQCI5JPdAWGaDqxRDvduvFAwbJDRTe6SeTg+94cVTP4etrLsAZgB54Bp2p6TwRtJtNtLKe6M+avrn1rPpxAQcq8PAQ0RHi0dmZ2MszZEgmInLS7MfP3ufWsW0pgwcBzDG8H2yI4Ry/i2KFJshFMFd08jw4zNdR7BSejQ/pcYpBIb7LjMYL0/fBNQY7oRoG/c5wQHSRF1SO+oKthHX8yNBRcTkAaZwmnHcojYqzwwRe4lF+Pwxs+jBl/XaRV/WBHdBr489rMZuBEc/kCaWBnYfs/XBs/GqyloNMkaaHK8jgF8CRiXEEB3t4Ov0iya6HAiqQ7iSCm72f/Nrn3qFtglwCDttfy9VzPEgo/LM2JGIBVIAegogjklsJ11pTG6krfPDvPov/p5RLObR4B9NzUNdo03hgFZPkfUaiQFspv0t9ZzI/w/32pjY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
