travis:
  secure:
    BINSTAR_TOKEN: PqTfgOYQVTuYu8PJfsScouWF8+5K3Lg8DcD+aantdXKO0MM2GSln4aPPLVGn2pz+85Z+830lChKFXMe0CwY2G4n+ayK9+rdNmulMzLeX8FaWJfRkcQuQ5VNsAqEC85qDaNE0YlSg4ZnnFmZlpHk6+s+NSADCGJP0zIMvPfksG9ilC8SFlM2o8RdbZvJtpQGpIN4OGTj4ezdyBYceQ/FWCyI1Wmh9SOQSKXu0LeH6c2pY+KcNC0oK37ehXaA1U7shjw2AAGpgR7PF2IxLTx+JxolCc26k2Mub04Wf+b+SYEkt/8Z0AWgmLq6mmHj555qmXR21WYQaFqjUEkyliVBpfpQSUccgpXA76VBPb7zblDK4hy8MtDe8vJk5Fu4wimUGmEjBILy4rvA1bxGX4SarPwOgKYcJrBle6twkNMXuQ4eXDH85wOu0a6CDvZAE8wXeyOa90XbPhnyKuWM+7xLF5xh3N2762kAMX5uy3Y7xRiHzMRgrUeAKKjV05XlFzhRLNO7h6kVLX8enAJUOasd5PrTveK8TEdcbgPD9TvHoUPc0WARToxyg66O6uHRmnQlQvFBICfYfipvxbv+myV9vEBJoql+WU1jH+cytwvTgwooC7c18UcKJJMeEMz7H1eMvNoegQHZX8eKd4P63PmOKXhCdBzEgzpMsDiJ5fIM+bAY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
